// Code generated by protoc-gen-defaults. DO NOT EDIT.

package credit

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"go.emailer.com/pb/user"
)

// BaseCreditServiceServer is the dummy implementation of the CreditServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseCreditServiceServer struct{}

// GetCredits is an unimplemented form of the method GetCredits
func (BaseCreditServiceServer) GetCredits(context.Context, *user.UserIdentifier) (*Credit, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ChargeCredits is an unimplemented form of the method ChargeCredits
func (BaseCreditServiceServer) ChargeCredits(context.Context, *ChargeCreditsRequest) (*Credit, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
