// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credit/credit.proto

package credit

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "go.emailer.com/pb/emailer"
	user "go.emailer.com/pb/user"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Credit struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Credits              int64                `protobuf:"varint,2,opt,name=credits,proto3" json:"credits,omitempty"`
	ExpireOn             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire_on,json=expireOn,proto3" json:"expire_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Credit) Reset()         { *m = Credit{} }
func (m *Credit) String() string { return proto.CompactTextString(m) }
func (*Credit) ProtoMessage()    {}
func (*Credit) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df5d32af6d231d, []int{0}
}

func (m *Credit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credit.Unmarshal(m, b)
}
func (m *Credit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credit.Marshal(b, m, deterministic)
}
func (m *Credit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credit.Merge(m, src)
}
func (m *Credit) XXX_Size() int {
	return xxx_messageInfo_Credit.Size(m)
}
func (m *Credit) XXX_DiscardUnknown() {
	xxx_messageInfo_Credit.DiscardUnknown(m)
}

var xxx_messageInfo_Credit proto.InternalMessageInfo

func (m *Credit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Credit) GetCredits() int64 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *Credit) GetExpireOn() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireOn
	}
	return nil
}

type ChargeCreditsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Credits              int64    `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeCreditsRequest) Reset()         { *m = ChargeCreditsRequest{} }
func (m *ChargeCreditsRequest) String() string { return proto.CompactTextString(m) }
func (*ChargeCreditsRequest) ProtoMessage()    {}
func (*ChargeCreditsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df5d32af6d231d, []int{1}
}

func (m *ChargeCreditsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeCreditsRequest.Unmarshal(m, b)
}
func (m *ChargeCreditsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeCreditsRequest.Marshal(b, m, deterministic)
}
func (m *ChargeCreditsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeCreditsRequest.Merge(m, src)
}
func (m *ChargeCreditsRequest) XXX_Size() int {
	return xxx_messageInfo_ChargeCreditsRequest.Size(m)
}
func (m *ChargeCreditsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeCreditsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeCreditsRequest proto.InternalMessageInfo

func (m *ChargeCreditsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChargeCreditsRequest) GetCredits() int64 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func init() {
	proto.RegisterType((*Credit)(nil), "go.emailer.com.Credit")
	proto.RegisterType((*ChargeCreditsRequest)(nil), "go.emailer.com.ChargeCreditsRequest")
}

func init() { proto.RegisterFile("credit/credit.proto", fileDescriptor_47df5d32af6d231d) }

var fileDescriptor_47df5d32af6d231d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xe5, 0xe4, 0x53, 0xfb, 0xd5, 0x55, 0x0b, 0x32, 0x08, 0xa2, 0x0c, 0x50, 0x55, 0x0c,
	0x9d, 0xec, 0xaa, 0x0c, 0x48, 0x8c, 0x2d, 0x12, 0x62, 0x40, 0x48, 0xa1, 0x2c, 0x2c, 0x95, 0x9b,
	0xdc, 0xa6, 0x16, 0x49, 0x1c, 0x1c, 0xa7, 0xea, 0xcc, 0xb3, 0xf0, 0x14, 0x4c, 0xbc, 0x4e, 0x79,
	0x02, 0x46, 0x94, 0x38, 0x19, 0xc2, 0x9f, 0x25, 0xf1, 0xf5, 0xb9, 0xbe, 0xe7, 0xe7, 0x23, 0xe3,
	0x03, 0x5f, 0x41, 0x20, 0x34, 0x33, 0x3f, 0x9a, 0x2a, 0xa9, 0x25, 0xe9, 0x87, 0x92, 0x42, 0xcc,
	0x45, 0x04, 0x8a, 0xfa, 0x32, 0x76, 0x4f, 0x43, 0x29, 0xc3, 0x08, 0x58, 0xa9, 0x2e, 0xf3, 0x15,
	0xd3, 0x22, 0x86, 0x4c, 0xf3, 0x38, 0x35, 0x07, 0xdc, 0xe3, 0x0d, 0x8f, 0x44, 0xc0, 0x35, 0xb0,
	0x7a, 0x51, 0x09, 0x7b, 0x79, 0x06, 0x8a, 0x15, 0x9f, 0x6a, 0xa3, 0xeb, 0xaf, 0xf9, 0x53, 0x6e,
	0x8a, 0xe1, 0x16, 0xb7, 0x66, 0xa5, 0x2f, 0xe9, 0x63, 0x4b, 0x04, 0x0e, 0x1a, 0xa0, 0x51, 0xc7,
	0xb3, 0x44, 0x40, 0x1c, 0xdc, 0x36, 0x44, 0x99, 0x63, 0x0d, 0xd0, 0xc8, 0xf6, 0xea, 0x92, 0x5c,
	0xe0, 0x0e, 0x6c, 0x53, 0xa1, 0x60, 0x21, 0x13, 0xc7, 0x1e, 0xa0, 0x51, 0x77, 0xe2, 0x52, 0xc3,
	0x47, 0x6b, 0x3e, 0x3a, 0xaf, 0xf9, 0xbc, 0xff, 0xa6, 0xf9, 0x2e, 0xb9, 0xec, 0x7e, 0xee, 0xc6,
	0xe8, 0xe5, 0x63, 0x6c, 0xfb, 0x10, 0x0c, 0xe7, 0xf8, 0x70, 0xb6, 0xe6, 0x2a, 0x04, 0xe3, 0x9f,
	0x79, 0xf0, 0x9c, 0x43, 0xa6, 0xc9, 0x10, 0xb7, 0x0b, 0xd8, 0x45, 0x0d, 0x33, 0xed, 0xbc, 0xed,
	0xde, 0xed, 0x7f, 0xca, 0xda, 0x47, 0x5e, 0xab, 0x50, 0x6e, 0x1a, 0x6c, 0x76, 0x83, 0x6d, 0xf2,
	0x8a, 0x70, 0xcf, 0x0c, 0xbc, 0x07, 0xb5, 0x11, 0x3e, 0x90, 0x2b, 0x8c, 0xaf, 0x41, 0x57, 0x26,
	0xe4, 0x84, 0x36, 0x83, 0xa5, 0x0f, 0xe5, 0x44, 0x48, 0xb4, 0x58, 0x09, 0x50, 0xee, 0xd1, 0x77,
	0xbd, 0x4a, 0xe7, 0x16, 0xf7, 0x1a, 0xb4, 0xe4, 0xec, 0x47, 0xe3, 0x2f, 0x97, 0xf9, 0x6b, 0xdc,
	0xd4, 0x7d, 0x74, 0x9a, 0x02, 0x4b, 0x97, 0xd5, 0x03, 0x58, 0xb6, 0xca, 0x0c, 0xcf, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x05, 0x90, 0x08, 0x38, 0x18, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreditServiceClient is the client API for CreditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreditServiceClient interface {
	GetCredits(ctx context.Context, in *user.UserIdentifier, opts ...grpc.CallOption) (*Credit, error)
	ChargeCredits(ctx context.Context, in *ChargeCreditsRequest, opts ...grpc.CallOption) (*Credit, error)
}

type creditServiceClient struct {
	cc *grpc.ClientConn
}

func NewCreditServiceClient(cc *grpc.ClientConn) CreditServiceClient {
	return &creditServiceClient{cc}
}

func (c *creditServiceClient) GetCredits(ctx context.Context, in *user.UserIdentifier, opts ...grpc.CallOption) (*Credit, error) {
	out := new(Credit)
	err := c.cc.Invoke(ctx, "/go.emailer.com.CreditService/GetCredits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ChargeCredits(ctx context.Context, in *ChargeCreditsRequest, opts ...grpc.CallOption) (*Credit, error) {
	out := new(Credit)
	err := c.cc.Invoke(ctx, "/go.emailer.com.CreditService/ChargeCredits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditServiceServer is the server API for CreditService service.
type CreditServiceServer interface {
	GetCredits(context.Context, *user.UserIdentifier) (*Credit, error)
	ChargeCredits(context.Context, *ChargeCreditsRequest) (*Credit, error)
}

func RegisterCreditServiceServer(s *grpc.Server, srv CreditServiceServer) {
	s.RegisterService(&_CreditService_serviceDesc, srv)
}

func _CreditService_GetCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.UserIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.CreditService/GetCredits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCredits(ctx, req.(*user.UserIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ChargeCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ChargeCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.CreditService/ChargeCredits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ChargeCredits(ctx, req.(*ChargeCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreditService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.emailer.com.CreditService",
	HandlerType: (*CreditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredits",
			Handler:    _CreditService_GetCredits_Handler,
		},
		{
			MethodName: "ChargeCredits",
			Handler:    _CreditService_ChargeCredits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credit/credit.proto",
}
