// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: membership/membership.proto

package membership

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on Membership with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Membership) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for DurationInMonth

	// no validation rules for Cost

	// no validation rules for Quantity

	return nil
}

// MembershipValidationError is the validation error returned by
// Membership.Validate if the designated constraints aren't met.
type MembershipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MembershipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MembershipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MembershipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MembershipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MembershipValidationError) ErrorName() string { return "MembershipValidationError" }

// Error satisfies the builtin error interface
func (e MembershipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMembership.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MembershipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MembershipValidationError{}

// Validate checks the field values on MembershipList with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MembershipList) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetMemberships() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MembershipListValidationError{
					field:  fmt.Sprintf("Memberships[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// MembershipListValidationError is the validation error returned by
// MembershipList.Validate if the designated constraints aren't met.
type MembershipListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MembershipListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MembershipListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MembershipListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MembershipListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MembershipListValidationError) ErrorName() string { return "MembershipListValidationError" }

// Error satisfies the builtin error interface
func (e MembershipListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMembershipList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MembershipListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MembershipListValidationError{}
