// Code generated by protoc-gen-go. DO NOT EDIT.
// source: membership/membership.proto

package membership

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "go.emailer.com/pb/emailer"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Membership struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationInMonth      int32    `protobuf:"varint,4,opt,name=duration_in_month,json=durationInMonth,proto3" json:"duration_in_month,omitempty"`
	Cost                 int32    `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity             int64    `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Membership) Reset()         { *m = Membership{} }
func (m *Membership) String() string { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()    {}
func (*Membership) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8c0607038ada2a7, []int{0}
}

func (m *Membership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Membership.Unmarshal(m, b)
}
func (m *Membership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Membership.Marshal(b, m, deterministic)
}
func (m *Membership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Membership.Merge(m, src)
}
func (m *Membership) XXX_Size() int {
	return xxx_messageInfo_Membership.Size(m)
}
func (m *Membership) XXX_DiscardUnknown() {
	xxx_messageInfo_Membership.DiscardUnknown(m)
}

var xxx_messageInfo_Membership proto.InternalMessageInfo

func (m *Membership) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Membership) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Membership) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Membership) GetDurationInMonth() int32 {
	if m != nil {
		return m.DurationInMonth
	}
	return 0
}

func (m *Membership) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Membership) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type MembershipList struct {
	Memberships          []*Membership `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MembershipList) Reset()         { *m = MembershipList{} }
func (m *MembershipList) String() string { return proto.CompactTextString(m) }
func (*MembershipList) ProtoMessage()    {}
func (*MembershipList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8c0607038ada2a7, []int{1}
}

func (m *MembershipList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipList.Unmarshal(m, b)
}
func (m *MembershipList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipList.Marshal(b, m, deterministic)
}
func (m *MembershipList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipList.Merge(m, src)
}
func (m *MembershipList) XXX_Size() int {
	return xxx_messageInfo_MembershipList.Size(m)
}
func (m *MembershipList) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipList.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipList proto.InternalMessageInfo

func (m *MembershipList) GetMemberships() []*Membership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

func init() {
	proto.RegisterType((*Membership)(nil), "go.emailer.com.Membership")
	proto.RegisterType((*MembershipList)(nil), "go.emailer.com.MembershipList")
}

func init() { proto.RegisterFile("membership/membership.proto", fileDescriptor_b8c0607038ada2a7) }

var fileDescriptor_b8c0607038ada2a7 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0xba, 0x0d, 0x7d, 0x0b, 0x95, 0x05, 0x91, 0xd0, 0xc9, 0x28, 0x3b, 0x15, 0x0f,
	0xe9, 0x98, 0x37, 0xf1, 0x24, 0x08, 0x0a, 0xce, 0x43, 0xbd, 0x09, 0x32, 0xfa, 0x27, 0xae, 0xc1,
	0xa6, 0xa9, 0x69, 0x2a, 0xec, 0xea, 0xf7, 0xf2, 0x03, 0xe9, 0x27, 0xf0, 0x28, 0x4d, 0xd9, 0xda,
	0x1d, 0xbc, 0xbd, 0xef, 0xf3, 0x3c, 0x79, 0x12, 0x7e, 0x81, 0xa9, 0x60, 0x22, 0x66, 0xaa, 0xca,
	0x78, 0x19, 0x74, 0x23, 0x2d, 0x95, 0xd4, 0x12, 0x3b, 0x1b, 0x49, 0x99, 0x88, 0x78, 0xce, 0x14,
	0x4d, 0xa4, 0x70, 0xa7, 0x1b, 0x29, 0x37, 0x39, 0x0b, 0x8c, 0x1b, 0xd7, 0xaf, 0x01, 0x13, 0xa5,
	0xde, 0xb6, 0x61, 0xd7, 0x4e, 0xb2, 0xe8, 0xad, 0x6e, 0x97, 0xf9, 0x17, 0x02, 0x58, 0xed, 0xeb,
	0xb0, 0x03, 0x03, 0x9e, 0x12, 0xe4, 0x21, 0xff, 0x38, 0x1c, 0xf0, 0x14, 0x9f, 0xc2, 0x48, 0x73,
	0x9d, 0x33, 0x32, 0x30, 0x52, 0xbb, 0x60, 0x0f, 0xec, 0x94, 0x55, 0x89, 0xe2, 0xa5, 0xe6, 0xb2,
	0x20, 0x96, 0xf1, 0xfa, 0x12, 0xbe, 0x80, 0x49, 0x5a, 0xab, 0xa8, 0x99, 0xd7, 0xbc, 0x58, 0x0b,
	0x59, 0xe8, 0x8c, 0x0c, 0x3d, 0xe4, 0x8f, 0xc2, 0x93, 0x9d, 0x71, 0x5f, 0xac, 0x1a, 0x19, 0x63,
	0x18, 0x26, 0xb2, 0xd2, 0x64, 0x64, 0x6c, 0x33, 0x63, 0x17, 0x8e, 0xde, 0xeb, 0xa8, 0xd0, 0x5c,
	0x6f, 0xc9, 0xd8, 0x43, 0xbe, 0x15, 0xee, 0xf7, 0x2b, 0xfb, 0xf7, 0x7b, 0x81, 0x3e, 0x7f, 0x16,
	0x96, 0x60, 0x62, 0xfe, 0x08, 0x4e, 0xf7, 0xfc, 0x07, 0x5e, 0x69, 0x7c, 0x0d, 0x76, 0xc7, 0xa7,
	0x22, 0xc8, 0xb3, 0x7c, 0x7b, 0xe9, 0xd2, 0x43, 0x42, 0xb4, 0x3b, 0x14, 0xf6, 0xe3, 0xcb, 0x17,
	0x98, 0x74, 0xd6, 0x13, 0x53, 0x1f, 0x3c, 0x61, 0xf8, 0x0e, 0x9c, 0xa6, 0xba, 0xc7, 0xe9, 0x8c,
	0xb6, 0x84, 0xe9, 0x8e, 0x30, 0xbd, 0x6d, 0x08, 0xbb, 0xb3, 0xff, 0xef, 0x69, 0x1a, 0x6e, 0x66,
	0xcf, 0xe7, 0x87, 0x81, 0xa0, 0x8c, 0x7b, 0xdf, 0x19, 0x8f, 0x4d, 0xdf, 0xe5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x15, 0x1d, 0x4d, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MembershipServiceClient interface {
	ListMembership(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MembershipList, error)
}

type membershipServiceClient struct {
	cc *grpc.ClientConn
}

func NewMembershipServiceClient(cc *grpc.ClientConn) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) ListMembership(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MembershipList, error) {
	out := new(MembershipList)
	err := c.cc.Invoke(ctx, "/go.emailer.com.MembershipService/ListMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
type MembershipServiceServer interface {
	ListMembership(context.Context, *empty.Empty) (*MembershipList, error)
}

func RegisterMembershipServiceServer(s *grpc.Server, srv MembershipServiceServer) {
	s.RegisterService(&_MembershipService_serviceDesc, srv)
}

func _MembershipService_ListMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ListMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.MembershipService/ListMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ListMembership(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MembershipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.emailer.com.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMembership",
			Handler:    _MembershipService_ListMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership/membership.proto",
}
