// Code generated by protoc-gen-defaults. DO NOT EDIT.

package log

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BaseLogServiceServer is the dummy implementation of the LogServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseLogServiceServer struct{}

// GetLogs is an unimplemented form of the method GetLogs
func (BaseLogServiceServer) GetLogs(context.Context, *GetLogRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
