// Code generated by protoc-gen-defaults. DO NOT EDIT.

package user

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/golang/protobuf/ptypes/empty"
)

// BaseUserServiceServer is the dummy implementation of the UserServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseUserServiceServer struct{}

// GetUser is an unimplemented form of the method GetUser
func (BaseUserServiceServer) GetUser(context.Context, *UserIdentifier) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// VerifyPassword is an unimplemented form of the method VerifyPassword
func (BaseUserServiceServer) VerifyPassword(context.Context, *UserLogin) (*UserLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// RegisterUser is an unimplemented form of the method RegisterUser
func (BaseUserServiceServer) RegisterUser(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// UpdateUser is an unimplemented form of the method UpdateUser
func (BaseUserServiceServer) UpdateUser(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ChangePassword is an unimplemented form of the method ChangePassword
func (BaseUserServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ForgetPassword is an unimplemented form of the method ForgetPassword
func (BaseUserServiceServer) ForgetPassword(context.Context, *ForgetPasswordRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ResetPassword is an unimplemented form of the method ResetPassword
func (BaseUserServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ListUserLastLogins is an unimplemented form of the method ListUserLastLogins
func (BaseUserServiceServer) ListUserLastLogins(context.Context, *UserIdentifier) (*UserLastLoginList, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// GetApiToken is an unimplemented form of the method GetApiToken
func (BaseUserServiceServer) GetApiToken(context.Context, *UserIdentifier) (*UserApiToken, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// GenerateApiToken is an unimplemented form of the method GenerateApiToken
func (BaseUserServiceServer) GenerateApiToken(context.Context, *UserIdentifier) (*UserApiToken, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// RevokeApiToken is an unimplemented form of the method RevokeApiToken
func (BaseUserServiceServer) RevokeApiToken(context.Context, *UserIdentifier) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
