// Code generated by protoc-gen-defaults. DO NOT EDIT.

package card

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/golang/protobuf/ptypes/empty"

	"go.emailer.com/pb/user"
)

// BaseCardServiceServer is the dummy implementation of the CardServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseCardServiceServer struct{}

// AddCard is an unimplemented form of the method AddCard
func (BaseCardServiceServer) AddCard(context.Context, *AddCardReq) (*CardIdentifier, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// UpdateCard is an unimplemented form of the method UpdateCard
func (BaseCardServiceServer) UpdateCard(context.Context, *UpdateCardReq) (*UpdateCardRes, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// DeleteCard is an unimplemented form of the method DeleteCard
func (BaseCardServiceServer) DeleteCard(context.Context, *CardIdentifier) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ListUserCards is an unimplemented form of the method ListUserCards
func (BaseCardServiceServer) ListUserCards(context.Context, *user.UserIdentifier) (*UserCardList, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// ChangeDefaultCard is an unimplemented form of the method ChangeDefaultCard
func (BaseCardServiceServer) ChangeDefaultCard(context.Context, *CardIdentifier) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
