// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: email_checker/email_checker.proto

package check

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on VerifyEmailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifyEmailRequest) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetEmails()) < 1 {
		return VerifyEmailRequestValidationError{
			field:  "Emails",
			reason: "value must contain at least 1 item(s)",
		}
	}

	return nil
}

// VerifyEmailRequestValidationError is the validation error returned by
// VerifyEmailRequest.Validate if the designated constraints aren't met.
type VerifyEmailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyEmailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyEmailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyEmailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyEmailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyEmailRequestValidationError) ErrorName() string {
	return "VerifyEmailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyEmailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyEmailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyEmailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyEmailRequestValidationError{}

// Validate checks the field values on VerifyEmailBulkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifyEmailBulkRequest) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetEmails()) < 1 {
		return VerifyEmailBulkRequestValidationError{
			field:  "Emails",
			reason: "value must contain at least 1 item(s)",
		}
	}

	// no validation rules for SendEmail

	if err := m._validateEmail(m.GetEmail()); err != nil {
		return VerifyEmailBulkRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
	}

	return nil
}

func (m *VerifyEmailBulkRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *VerifyEmailBulkRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// VerifyEmailBulkRequestValidationError is the validation error returned by
// VerifyEmailBulkRequest.Validate if the designated constraints aren't met.
type VerifyEmailBulkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyEmailBulkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyEmailBulkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyEmailBulkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyEmailBulkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyEmailBulkRequestValidationError) ErrorName() string {
	return "VerifyEmailBulkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyEmailBulkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyEmailBulkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyEmailBulkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyEmailBulkRequestValidationError{}

// Validate checks the field values on VerifyEmailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifyEmailResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetEmails() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VerifyEmailResponseValidationError{
					field:  fmt.Sprintf("Emails[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalEmails

	// no validation rules for ValidEmails

	// no validation rules for InvalidEmails

	return nil
}

// VerifyEmailResponseValidationError is the validation error returned by
// VerifyEmailResponse.Validate if the designated constraints aren't met.
type VerifyEmailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyEmailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyEmailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyEmailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyEmailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyEmailResponseValidationError) ErrorName() string {
	return "VerifyEmailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyEmailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyEmailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyEmailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyEmailResponseValidationError{}

// Validate checks the field values on EmailStatus with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *EmailStatus) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Email

	// no validation rules for Valid

	return nil
}

// EmailStatusValidationError is the validation error returned by
// EmailStatus.Validate if the designated constraints aren't met.
type EmailStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmailStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmailStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmailStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmailStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmailStatusValidationError) ErrorName() string { return "EmailStatusValidationError" }

// Error satisfies the builtin error interface
func (e EmailStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmailStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmailStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmailStatusValidationError{}

// Validate checks the field values on CsvResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CsvResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	if v, ok := interface{}(m.GetSubmittedOn()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CsvResponseValidationError{
				field:  "SubmittedOn",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetGeneratedOn()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CsvResponseValidationError{
				field:  "GeneratedOn",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TotalEmails

	// no validation rules for ValidEmails

	// no validation rules for InvalidEmails

	// no validation rules for DownloadUrl

	return nil
}

// CsvResponseValidationError is the validation error returned by
// CsvResponse.Validate if the designated constraints aren't met.
type CsvResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CsvResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CsvResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CsvResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CsvResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CsvResponseValidationError) ErrorName() string { return "CsvResponseValidationError" }

// Error satisfies the builtin error interface
func (e CsvResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCsvResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CsvResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CsvResponseValidationError{}

// Validate checks the field values on CsvList with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *CsvList) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetCsvList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CsvListValidationError{
					field:  fmt.Sprintf("CsvList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// CsvListValidationError is the validation error returned by CsvList.Validate
// if the designated constraints aren't met.
type CsvListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CsvListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CsvListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CsvListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CsvListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CsvListValidationError) ErrorName() string { return "CsvListValidationError" }

// Error satisfies the builtin error interface
func (e CsvListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCsvList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CsvListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CsvListValidationError{}
