// Code generated by protoc-gen-defaults. DO NOT EDIT.

package check

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/golang/protobuf/ptypes/empty"

	"go.emailer.com/pb/user"
)

// BaseEmailCheckerServiceServer is the dummy implementation of the EmailCheckerServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseEmailCheckerServiceServer struct{}

// VerifyEmail is an unimplemented form of the method VerifyEmail
func (BaseEmailCheckerServiceServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// VerifyEmailBulk is an unimplemented form of the method VerifyEmailBulk
func (BaseEmailCheckerServiceServer) VerifyEmailBulk(context.Context, *VerifyEmailBulkRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}

// GetProcessedCsv is an unimplemented form of the method GetProcessedCsv
func (BaseEmailCheckerServiceServer) GetProcessedCsv(context.Context, *user.UserIdentifier) (*CsvList, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
