// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email_checker/email_checker.proto

package check

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/lyft/protoc-gen-validate/validate"
	user "go.emailer.com/pb/user"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyEmailRequest struct {
	Emails               []string `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{0}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

type VerifyEmailBulkRequest struct {
	Emails               []string `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	SendEmail            bool     `protobuf:"varint,2,opt,name=send_email,json=sendEmail,proto3" json:"send_email,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailBulkRequest) Reset()         { *m = VerifyEmailBulkRequest{} }
func (m *VerifyEmailBulkRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailBulkRequest) ProtoMessage()    {}
func (*VerifyEmailBulkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{1}
}

func (m *VerifyEmailBulkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailBulkRequest.Unmarshal(m, b)
}
func (m *VerifyEmailBulkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailBulkRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailBulkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailBulkRequest.Merge(m, src)
}
func (m *VerifyEmailBulkRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailBulkRequest.Size(m)
}
func (m *VerifyEmailBulkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailBulkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailBulkRequest proto.InternalMessageInfo

func (m *VerifyEmailBulkRequest) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *VerifyEmailBulkRequest) GetSendEmail() bool {
	if m != nil {
		return m.SendEmail
	}
	return false
}

func (m *VerifyEmailBulkRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VerifyEmailResponse struct {
	Emails               []*EmailStatus `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	TotalEmails          int64          `protobuf:"varint,2,opt,name=total_emails,json=totalEmails,proto3" json:"total_emails,omitempty"`
	ValidEmails          int64          `protobuf:"varint,3,opt,name=valid_emails,json=validEmails,proto3" json:"valid_emails,omitempty"`
	InvalidEmails        int64          `protobuf:"varint,4,opt,name=invalid_emails,json=invalidEmails,proto3" json:"invalid_emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{2}
}

func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(m, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

func (m *VerifyEmailResponse) GetEmails() []*EmailStatus {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *VerifyEmailResponse) GetTotalEmails() int64 {
	if m != nil {
		return m.TotalEmails
	}
	return 0
}

func (m *VerifyEmailResponse) GetValidEmails() int64 {
	if m != nil {
		return m.ValidEmails
	}
	return 0
}

func (m *VerifyEmailResponse) GetInvalidEmails() int64 {
	if m != nil {
		return m.InvalidEmails
	}
	return 0
}

type EmailStatus struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailStatus) Reset()         { *m = EmailStatus{} }
func (m *EmailStatus) String() string { return proto.CompactTextString(m) }
func (*EmailStatus) ProtoMessage()    {}
func (*EmailStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{3}
}

func (m *EmailStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailStatus.Unmarshal(m, b)
}
func (m *EmailStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailStatus.Marshal(b, m, deterministic)
}
func (m *EmailStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailStatus.Merge(m, src)
}
func (m *EmailStatus) XXX_Size() int {
	return xxx_messageInfo_EmailStatus.Size(m)
}
func (m *EmailStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EmailStatus proto.InternalMessageInfo

func (m *EmailStatus) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailStatus) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type CsvResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubmittedOn          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=submitted_on,json=submittedOn,proto3" json:"submitted_on,omitempty"`
	GeneratedOn          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=generated_on,json=generatedOn,proto3" json:"generated_on,omitempty"`
	TotalEmails          int64                `protobuf:"varint,4,opt,name=total_emails,json=totalEmails,proto3" json:"total_emails,omitempty"`
	ValidEmails          int64                `protobuf:"varint,5,opt,name=valid_emails,json=validEmails,proto3" json:"valid_emails,omitempty"`
	InvalidEmails        int64                `protobuf:"varint,6,opt,name=invalid_emails,json=invalidEmails,proto3" json:"invalid_emails,omitempty"`
	DownloadUrl          string               `protobuf:"bytes,7,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CsvResponse) Reset()         { *m = CsvResponse{} }
func (m *CsvResponse) String() string { return proto.CompactTextString(m) }
func (*CsvResponse) ProtoMessage()    {}
func (*CsvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{4}
}

func (m *CsvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CsvResponse.Unmarshal(m, b)
}
func (m *CsvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CsvResponse.Marshal(b, m, deterministic)
}
func (m *CsvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CsvResponse.Merge(m, src)
}
func (m *CsvResponse) XXX_Size() int {
	return xxx_messageInfo_CsvResponse.Size(m)
}
func (m *CsvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CsvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CsvResponse proto.InternalMessageInfo

func (m *CsvResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CsvResponse) GetSubmittedOn() *timestamp.Timestamp {
	if m != nil {
		return m.SubmittedOn
	}
	return nil
}

func (m *CsvResponse) GetGeneratedOn() *timestamp.Timestamp {
	if m != nil {
		return m.GeneratedOn
	}
	return nil
}

func (m *CsvResponse) GetTotalEmails() int64 {
	if m != nil {
		return m.TotalEmails
	}
	return 0
}

func (m *CsvResponse) GetValidEmails() int64 {
	if m != nil {
		return m.ValidEmails
	}
	return 0
}

func (m *CsvResponse) GetInvalidEmails() int64 {
	if m != nil {
		return m.InvalidEmails
	}
	return 0
}

func (m *CsvResponse) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

type CsvList struct {
	CsvList              []*CsvResponse `protobuf:"bytes,1,rep,name=csv_list,json=csvList,proto3" json:"csv_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CsvList) Reset()         { *m = CsvList{} }
func (m *CsvList) String() string { return proto.CompactTextString(m) }
func (*CsvList) ProtoMessage()    {}
func (*CsvList) Descriptor() ([]byte, []int) {
	return fileDescriptor_589a334c48052b1e, []int{5}
}

func (m *CsvList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CsvList.Unmarshal(m, b)
}
func (m *CsvList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CsvList.Marshal(b, m, deterministic)
}
func (m *CsvList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CsvList.Merge(m, src)
}
func (m *CsvList) XXX_Size() int {
	return xxx_messageInfo_CsvList.Size(m)
}
func (m *CsvList) XXX_DiscardUnknown() {
	xxx_messageInfo_CsvList.DiscardUnknown(m)
}

var xxx_messageInfo_CsvList proto.InternalMessageInfo

func (m *CsvList) GetCsvList() []*CsvResponse {
	if m != nil {
		return m.CsvList
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyEmailRequest)(nil), "go.emailer.com.VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailBulkRequest)(nil), "go.emailer.com.VerifyEmailBulkRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "go.emailer.com.VerifyEmailResponse")
	proto.RegisterType((*EmailStatus)(nil), "go.emailer.com.EmailStatus")
	proto.RegisterType((*CsvResponse)(nil), "go.emailer.com.CsvResponse")
	proto.RegisterType((*CsvList)(nil), "go.emailer.com.CsvList")
}

func init() { proto.RegisterFile("email_checker/email_checker.proto", fileDescriptor_589a334c48052b1e) }

var fileDescriptor_589a334c48052b1e = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xed, 0x36, 0x7f, 0xd6, 0xfd, 0x25, 0xd2, 0xf6, 0xa7, 0x26, 0xb8, 0x82, 0xa6, 0x46,
	0xa0, 0x9c, 0x6c, 0x29, 0x95, 0x10, 0x1c, 0x38, 0x90, 0x28, 0x42, 0x20, 0xa4, 0x82, 0x4b, 0x7b,
	0xe0, 0x62, 0x1c, 0x7b, 0x12, 0x56, 0xb5, 0xbd, 0x61, 0x77, 0x6d, 0x54, 0x89, 0x47, 0xe0, 0xc4,
	0x6b, 0xf0, 0x00, 0x48, 0x9c, 0x78, 0x1d, 0xde, 0x02, 0x79, 0xbd, 0x8e, 0xe2, 0xa4, 0xb4, 0x70,
	0x89, 0xb2, 0xdf, 0x7c, 0xdf, 0xec, 0xcc, 0xe7, 0x99, 0x45, 0xc7, 0x90, 0x04, 0x24, 0xf6, 0xc3,
	0x0f, 0x10, 0x5e, 0x02, 0x73, 0x6b, 0x27, 0x67, 0xc9, 0xa8, 0xa0, 0xb8, 0xb3, 0xa0, 0x8e, 0xc4,
	0x81, 0x39, 0x21, 0x4d, 0xac, 0xc3, 0x05, 0xa5, 0x8b, 0x18, 0x5c, 0x19, 0x9d, 0x65, 0x73, 0x17,
	0x92, 0xa5, 0xb8, 0x2a, 0xc9, 0xd6, 0xd1, 0x66, 0x50, 0x90, 0x04, 0xb8, 0x08, 0x92, 0xa5, 0x22,
	0x74, 0x33, 0x0e, 0xcc, 0x2d, 0x7e, 0x14, 0xd0, 0xcb, 0x83, 0x98, 0x44, 0x81, 0x00, 0xb7, 0xfa,
	0x53, 0x06, 0xec, 0xc7, 0x08, 0x5f, 0x00, 0x23, 0xf3, 0xab, 0x69, 0x71, 0xb9, 0x07, 0x1f, 0x33,
	0xe0, 0x02, 0xdb, 0xa8, 0x21, 0x8b, 0xe1, 0x7d, 0x6d, 0x60, 0x0c, 0xdb, 0x63, 0xf4, 0xe3, 0xd7,
	0x4f, 0x63, 0xf7, 0xab, 0xa6, 0xb7, 0x34, 0x4f, 0x45, 0xec, 0xcf, 0xe8, 0x60, 0x4d, 0x39, 0xce,
	0xe2, 0xcb, 0x7f, 0x50, 0xe3, 0xbb, 0x08, 0x71, 0x48, 0x23, 0x5f, 0x1e, 0xfb, 0xfa, 0x40, 0x1b,
	0xb6, 0xbc, 0x76, 0x81, 0xc8, 0x6c, 0xf8, 0x08, 0xed, 0x96, 0x11, 0x63, 0xa0, 0x0d, 0xdb, 0xe3,
	0x76, 0x91, 0x61, 0x87, 0xe9, 0xef, 0x35, 0xaf, 0xc4, 0xed, 0xef, 0x1a, 0xda, 0xaf, 0x15, 0xce,
	0x97, 0x34, 0xe5, 0x80, 0x4f, 0x6a, 0x77, 0x9b, 0xa3, 0x43, 0xa7, 0x6e, 0xac, 0x23, 0xe9, 0x67,
	0x22, 0x10, 0x19, 0x5f, 0x15, 0x73, 0x8c, 0xf6, 0x04, 0x15, 0x41, 0xec, 0x2b, 0x69, 0x51, 0x8e,
	0xe1, 0x99, 0x12, 0x9b, 0xae, 0x28, 0xd2, 0xb9, 0x8a, 0x62, 0x94, 0x14, 0x89, 0x29, 0xca, 0x03,
	0xd4, 0x21, 0x69, 0x8d, 0xb4, 0x23, 0x49, 0xff, 0x29, 0xb4, 0xa4, 0xd9, 0x4f, 0x90, 0xb9, 0x56,
	0x03, 0xfe, 0xbf, 0xea, 0x54, 0x2b, 0x3a, 0x55, 0xed, 0x15, 0xa8, 0xd4, 0x28, 0x67, 0xca, 0x83,
	0xfd, 0x4d, 0x47, 0xe6, 0x84, 0xe7, 0xab, 0x66, 0x3b, 0x48, 0x27, 0x91, 0x12, 0xea, 0x24, 0xc2,
	0x4f, 0xd1, 0x1e, 0xcf, 0x66, 0x09, 0x11, 0x02, 0x22, 0x9f, 0xa6, 0x52, 0x6c, 0x8e, 0x2c, 0xa7,
	0x1c, 0x17, 0xa7, 0x1a, 0x17, 0xe7, 0x6d, 0x35, 0x2e, 0x9e, 0xb9, 0xe2, 0x9f, 0xa6, 0x85, 0x7c,
	0x01, 0x29, 0xb0, 0x40, 0xc9, 0x8d, 0xdb, 0xe5, 0x2b, 0xfe, 0x69, 0xba, 0xe5, 0xe2, 0xce, 0xed,
	0x2e, 0xee, 0xfe, 0x8d, 0x8b, 0x8d, 0x6b, 0x5c, 0x2c, 0x32, 0x45, 0xf4, 0x53, 0x1a, 0xd3, 0x20,
	0xf2, 0x33, 0x16, 0xf7, 0x9b, 0xd2, 0x04, 0xb3, 0xc2, 0xce, 0x59, 0x6c, 0x3f, 0x43, 0xcd, 0x09,
	0xcf, 0x5f, 0x11, 0x2e, 0xf0, 0x23, 0xd4, 0x0a, 0x79, 0xee, 0xc7, 0x84, 0x8b, 0x3f, 0xcd, 0xc5,
	0x9a, 0xaf, 0x5e, 0x33, 0x2c, 0x75, 0xa3, 0x2f, 0x3a, 0xda, 0x97, 0x17, 0x4e, 0xca, 0x65, 0x3d,
	0x03, 0x96, 0x93, 0x10, 0xf0, 0x05, 0x32, 0xd7, 0x86, 0x0f, 0xdb, 0x9b, 0xc9, 0xb6, 0x57, 0xca,
	0xba, 0x7f, 0x23, 0x47, 0x7d, 0xd0, 0x37, 0xa8, 0xbb, 0xb1, 0x53, 0xf8, 0xe1, 0x0d, 0xba, 0xb5,
	0xa5, 0xb3, 0x0e, 0xb6, 0x3e, 0xd3, 0xb4, 0x78, 0x31, 0xf0, 0x4b, 0xd4, 0x7d, 0x0e, 0xe2, 0x35,
	0xa3, 0x21, 0x70, 0x0e, 0xd1, 0x84, 0xe7, 0xf8, 0xde, 0x66, 0xca, 0x73, 0x0e, 0xec, 0x45, 0x04,
	0xa9, 0x20, 0x73, 0x02, 0xcc, 0xea, 0x5d, 0xe3, 0x4d, 0x61, 0xc7, 0xf8, 0xce, 0xbb, 0x5e, 0x3d,
	0xe2, 0x2e, 0x67, 0xae, 0x7c, 0xc7, 0x66, 0x0d, 0x79, 0xed, 0xc9, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x00, 0xc7, 0x03, 0xeb, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailCheckerServiceClient is the client API for EmailCheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailCheckerServiceClient interface {
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	VerifyEmailBulk(ctx context.Context, in *VerifyEmailBulkRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetProcessedCsv(ctx context.Context, in *user.UserIdentifier, opts ...grpc.CallOption) (*CsvList, error)
}

type emailCheckerServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailCheckerServiceClient(cc *grpc.ClientConn) EmailCheckerServiceClient {
	return &emailCheckerServiceClient{cc}
}

func (c *emailCheckerServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, "/go.emailer.com.EmailCheckerService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailCheckerServiceClient) VerifyEmailBulk(ctx context.Context, in *VerifyEmailBulkRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/go.emailer.com.EmailCheckerService/VerifyEmailBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailCheckerServiceClient) GetProcessedCsv(ctx context.Context, in *user.UserIdentifier, opts ...grpc.CallOption) (*CsvList, error) {
	out := new(CsvList)
	err := c.cc.Invoke(ctx, "/go.emailer.com.EmailCheckerService/GetProcessedCsv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailCheckerServiceServer is the server API for EmailCheckerService service.
type EmailCheckerServiceServer interface {
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	VerifyEmailBulk(context.Context, *VerifyEmailBulkRequest) (*empty.Empty, error)
	GetProcessedCsv(context.Context, *user.UserIdentifier) (*CsvList, error)
}

func RegisterEmailCheckerServiceServer(s *grpc.Server, srv EmailCheckerServiceServer) {
	s.RegisterService(&_EmailCheckerService_serviceDesc, srv)
}

func _EmailCheckerService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailCheckerServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.EmailCheckerService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailCheckerServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailCheckerService_VerifyEmailBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailCheckerServiceServer).VerifyEmailBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.EmailCheckerService/VerifyEmailBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailCheckerServiceServer).VerifyEmailBulk(ctx, req.(*VerifyEmailBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailCheckerService_GetProcessedCsv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.UserIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailCheckerServiceServer).GetProcessedCsv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.emailer.com.EmailCheckerService/GetProcessedCsv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailCheckerServiceServer).GetProcessedCsv(ctx, req.(*user.UserIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailCheckerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.emailer.com.EmailCheckerService",
	HandlerType: (*EmailCheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyEmail",
			Handler:    _EmailCheckerService_VerifyEmail_Handler,
		},
		{
			MethodName: "VerifyEmailBulk",
			Handler:    _EmailCheckerService_VerifyEmailBulk_Handler,
		},
		{
			MethodName: "GetProcessedCsv",
			Handler:    _EmailCheckerService_GetProcessedCsv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email_checker/email_checker.proto",
}
