// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: email/email.proto

package email

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on SendEmailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *SendEmailRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	if utf8.RuneCountInString(m.GetUserId()) < 1 {
		return SendEmailRequestValidationError{
			field:  "UserId",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for Subject

	// no validation rules for Body

	if len(m.GetEmails()) < 1 {
		return SendEmailRequestValidationError{
			field:  "Emails",
			reason: "value must contain at least 1 item(s)",
		}
	}

	return nil
}

// SendEmailRequestValidationError is the validation error returned by
// SendEmailRequest.Validate if the designated constraints aren't met.
type SendEmailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailRequestValidationError) ErrorName() string { return "SendEmailRequestValidationError" }

// Error satisfies the builtin error interface
func (e SendEmailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailRequestValidationError{}
