// Code generated by protoc-gen-defaults. DO NOT EDIT.

package email

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/golang/protobuf/ptypes/empty"
)

// BaseEmailServiceServer is the dummy implementation of the EmailServiceServer. Embed this into your own implementation
// to add new methods without breaking builds.
type BaseEmailServiceServer struct{}

// SendEmail is an unimplemented form of the method SendEmail
func (BaseEmailServiceServer) SendEmail(context.Context, *SendEmailRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, codes.Unimplemented.String())
}
